version: '3'

services:
  www:
    build: .
    depends_on:
      - db
    ports:
      - "8001:80"
    volumes:
      - ./www:/var/www/html/
    networks:
      - wpsite
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./db:/opt/data
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: stw
      MYSQL_USER: stw
      MYSQL_PASSWORD: stw
    networks:
      - wpsite
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - wpsite
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
networks:
  wpsite:
volumes:
  db_data:
